//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class college
    {
        public int Collegeid { get; set; }
        public string collegeName { get; set; }
        public string location { get; set; }
        public Nullable<decimal> cutOffPercentage { get; set; }
        public Nullable<int> NumberofseatsAvailable { get; set; }
    }
}
