//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManagementEntities
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class collegemanagementsystemEntities : DbContext
    {
        public collegemanagementsystemEntities()
            : base("name=collegemanagementsystemEntities")
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<College> Colleges { get; set; }
        public virtual DbSet<Student> Students { get; set; }

        public List<Student> ToList()
        {
            throw new NotImplementedException();
        }
    }
}
