//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class college
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public college()
        {
            this.students = new HashSet<student>();
        }
    
        public int Collegeid { get; set; }
        public string collegeName { get; set; }
        public string location { get; set; }
        public Nullable<decimal> cutOffPercentage { get; set; }
        public Nullable<int> NumberofseatsAvailable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student> students { get; set; }
    }
}
