//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int studentid { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> PercentageObtained { get; set; }
        public Nullable<int> Collegeid { get; set; }
    
        public virtual college college { get; set; }
    }
}
