//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;

    public partial class ApplyForjob
    {
        public int Companyid { get; set; }
        public string CompanyName { get; set; }
        public string CandidatName { get; set; }
        public Nullable<decimal> mobileNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> Genderid { get; set; }
        public string CurrentRole { get; set; }
        public string collegename { get; set; }
        public string PreOrgName { get; set; }

        public virtual Contact Contact { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
