//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;

    public partial class Contact
    {

        public Contact()
        {
            this.ApplyForjobs = new HashSet<ApplyForjob>();
        }

        public int ContactId { get; set; }
        public string ContactedBy { get; set; }

        public virtual ICollection<ApplyForjob> ApplyForjobs { get; set; }
    }
}
